apiVersion: v1
kind: Service
metadata:
    name: internal-fusionauth-service
    labels:
        task: fusionauth
spec:
    type: NodePort
    ports:
        - port: 9011
          protocol: TCP
    selector:
        task: fusionauth