[package]
name = "squadov_api_server"
version = "0.1.0"
authors = ["Michael Bao <mike.h.bao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"
actix-cors = "0.4.1"
serde = "1.0.116"
log = "0.4.0"
env_logger = "0.7.1"
derive_more = "0.99.11"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
toml = "0.5"
structopt = "0.3"
uuid = { version = "0.8", features = ["serde", "v4"] }
sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "json", "ipnetwork", "uuid", "chrono" ] }