[package]
name = "squadov_api_server"
version = "0.1.0"
authors = ["GRCHive, Inc. <mike@squadov.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"
actix-cors = "0.4.1"
actix-service = "1.0.6"
async-trait = "0.1.41"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.59"
log = "0.4.0"
env_logger = "0.7.1"
derive_more = "0.99.11"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
toml = "0.5"
structopt = "0.3"
uuid = { version = "0.8", features = ["serde", "v4"] }
sqlx = { path="deps/cargo/sqlx", version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "json", "ipnetwork", "uuid", "chrono", "offline"] }
futures = "0.3.6"
futures-util = "0.3.6"
chrono = { version = "0.4.19", features = ["serde"] }
url = "2.1.1"
base64 = "0.13.0"
jsonwebtoken = "7.2.0"
sha2 = "0.9.1"
hex = "0.4.2"
openssl = "0.10"
openssl-sys = "0.9.58"
percent-encoding = "2.1.0"