[workspace]
members = [
    "server",
    "lib/squadov_common",
    "tools/hearthstone_power_parser"
]
default-members = [
    "server",
    "lib/squadov_common",
    "tools/hearthstone_power_parser"
]
exclude = ["deps/cargo/sqlx"]