version: "3.8"
services:
    postgres:
        image: postgres:12.4
        volumes:
            - type: volume
              source: db-data
              target: /var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=${POSTGRES_USER}"
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
            - "POSTGRES_DB=squadov"
        ports:
            - "5432:5432"
        networks:
            c3p0:
                ipv4_address: "172.22.0.2"
    fusionauth:
        image: "fusionauth/fusionauth-app:1.19.8"
        volumes:
            - type: volume
              source: fa-config
              target: /usr/local/fusionauth/config
        environment:
            - "DATABASE_URL=jdbc:postgresql://172.22.0.2:5432/fusionauth?timezone=UTC"
            - "DATABASE_ROOT_USER=${POSTGRES_USER}"
            - "DATABASE_ROOT_PASSWORD=${POSTGRES_PASSWORD}"
            - "DATABASE_USER=${FUSIONAUTH_DB_USER}"
            - "DATABASE_PASSWORD=${FUSIONAUTH_DB_PASSWORD}"
            - "FUSIONAUTH_MEMORY=1G"
            - "FUSIONAUTH_SEARCH_ENGINE_TYPE=database"
        ports:
            - "9011:9011"
        networks:
            c3p0:
                ipv4_address: "172.22.0.3"
        depends_on:
            - postgres
volumes:
    db-data:
    fa-config:

networks:
    c3p0:
        ipam:
            driver: default
            config:
                - subnet: "172.22.0.0/24"