apiVersion: v1
kind: Service
metadata:
    name: internal-admin-service
    labels:
        task: admin
spec:
    type: NodePort
    ports:
        - port: 3000
          protocol: TCP
    selector:
        task: admin