apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
    labels:
        task: api
spec:
    replicas: 4
    selector:
        matchLabels:
            task: api
    template:
        metadata:
            labels:
                task: api
        spec:
            nodeSelector:
                eks.amazonaws.com/compute-type: fargate
            dnsConfig:
                options:
                    - name: ndots
                      value: "2"
                    - name: attempts
                      value: "3"
            containers:
                - name: api
                  image: registry.gitlab.com/squadov/squadovapiserver/{{ .Values.environment }}/squadov_api_server:{{ .Values.commitHash }}
                  ports:
                    - containerPort: 8080
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 60
                    timeoutSeconds: 20
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 60
                    timeoutSeconds: 20
                  resources:
                    requests:
                        cpu: "1000m"
                        memory: "5Gi"
                  env:
                    - name: FFMPEG_BINARY_PATH
                      value: ffmpeg
                    - name: SQUADOV_DB_CONNECTIONS
                      value: "512"
                    - name: SQUADOV_DB_HEAVY_CONNECTIONS
                      value: "256"
                    - name: "WORKERS"
                      value: "32"
            imagePullSecrets:
                - name: regcred