apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
    labels:
        task: api
spec:
    replicas: 1
    selector:
        matchLabels:
            task: api
    template:
        metadata:
            labels:
                task: api
        spec:
            containers:
                - name: api
                  image: registry.gitlab.com/squadov/squadovapiserver/{{ .Values.environment }}/squadov_api_server:{{ .Values.commitHash }}
                  ports:
                    - containerPort: 8080
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 5
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                  resources:
                    requests:
                        cpu: "1000m"
                        memory: "2Gi"
                  env:
                    - name: FFMPEG_BINARY_PATH
                      value: ffmpeg
            imagePullSecrets:
                - name: regcred