apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
    labels:
        task: api
spec:
    replicas: 2
    selector:
        matchLabels:
            task: api
    template:
        metadata:
            labels:
                task: api
        spec:
            nodeSelector:
                eks.amazonaws.com/compute-type: fargate
            containers:
                - name: api
                  image: registry.gitlab.com/squadov/squadovapiserver/{{ .Values.environment }}/squadov_api_server:{{ .Values.commitHash }}
                  ports:
                    - containerPort: 8080
                  livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 60
                    timeoutSeconds: 20
                  readinessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 60
                    timeoutSeconds: 20
                  resources:
                    requests:
                        cpu: "1000m"
                        memory: "3Gi"
                  env:
                    - name: FFMPEG_BINARY_PATH
                      value: ffmpeg
                    - name: SQUADOV_DB_CONNECTIONS
                      value: "1024"
                    - name: SQUADOV_DB_HEAVY_CONNECTIONS
                      value: "512"
            imagePullSecrets:
                - name: regcred