apiVersion: v1
kind: Service
metadata:
    name: internal-api-service
    annotations:
        cloud.google.com/backend-config: '{"default": "api-backendconfig"}'
    labels:
        task: api
spec:
    type: NodePort
    ports:
        - port: 8080
          protocol: TCP
    selector:
        task: api