apiVersion: v1
kind: Service
metadata:
    name: internal-api-service
    labels:
        task: api
    annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /healthz
spec:
    type: NodePort
    ports:
        - port: 8080
          protocol: TCP
    selector:
        task: api