apiVersion: apps/v1
kind: Deployment
metadata:
    name: singleton-event-processing
    labels:
        task: event
spec:
    replicas: 1
    selector:
        matchLabels:
            task: event
    template:
        metadata:
            labels:
                task: event
        spec:
            nodeSelector:
                eks.amazonaws.com/compute-type: fargate
            containers:
                - name: worker
                  image: "registry.gitlab.com/squadov/squadovapiserver/{{ .Values.environment }}/singleton_event_processing:{{ .Values.commitHash }}"
                  env:
                    - name: DB_CONNS
                      value: "24"
                    - name: WORKERS
                      value: "8"
                  resources:
                    requests:
                        cpu: "250m"
                        memory: "1Gi"
            imagePullSecrets:
                - name: regcred