- name: Deploy Support Infrastructure
  vars_files:
    - common/env.yml
  hosts: "{{ shosts }}"
  tasks:
    - name: Docker Login
      shell: echo {{ env.GITLAB_REGISTRY_TOKEN }} | docker login --username {{ env.GITLAB_USERNAME }} --password-stdin registry.gitlab.com
    - name: Copy Production Docker Compose
      copy:
        src: ../docker/prod-compose.yml
        dest: /squadov/docker-compose.yml
    - name: Pull
      command: 
        cmd: ./docker-compose pull
        chdir: /squadov
      environment: "{{ env }}"
    - name: Up
      command: 
        cmd: ./docker-compose up --detach
        chdir: /squadov
      environment: "{{ env }}"