- name: Deploy Web App and API
  vars_files:
    - common/env.yml
  hosts: "{{ shosts }}"
  tasks:
    - name: Docker Login
      shell: echo {{ env.GITLAB_REGISTRY_TOKEN }} | docker login --username {{ env.GITLAB_USERNAME }} --password-stdin registry.gitlab.com
    - name: Copy Production Docker Compose
      copy:
        src: ../docker/prod-app-compose.yml
        dest: /webapp/docker-compose.yml
    - name: Pull
      command: 
        cmd: ../squadov/docker-compose pull
        chdir: /webapp
      environment: "{{ env }}"
    - name: Up
      command: 
        cmd: ../squadov/docker-compose up --detach
        chdir: /webapp
      environment: "{{ env }}"