apiVersion: v1
kind: Service
metadata:
    name: internal-blog-service
    labels:
        task: blog
spec:
    type: NodePort
    ports:
        - port: 80
          protocol: TCP
    selector:
        task: blog